import type { Metadata } from "next";

import { Geist, DM_Sans, Space_Mono } from "next/font/google";
import "./globals.css";

import { cookies } from "next/headers";

import { ClientProviders } from "@/components/ClientProviders";
import { API_BASE_URL } from "@/lib/api";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  variable: "--font-space-mono",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getUser() {
  const cookieStore = await cookies();
  const sessionCookie = cookieStore.get("sessionId")?.value;

  const res = await fetch(`${API_BASE_URL}/auth/me`, {
    headers: {
      Cookie: `sessionId=${sessionCookie}`,
    },
    cache: "no-store",
  });

  if (!res.ok) return null;

  const json = await res.json();

  return json.data.user; // ← drill into the right path
}

// then in layout:
const user = await getUser();
const userId = user?.id;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${dmSans.variable} ${spaceMono.variable} font-sans ${geist.variable}`}
    >
      <ClientProviders userId={userId}>
        <body className="min-h-full flex flex-col">{children}</body>
      </ClientProviders>
    </html>
  );
}
